project_id = "vzkycacuovszpcioeusm"

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.langflow-chat]
verify_jwt = false

[functions.composio-auth]
verify_jwt = false

[functions.financial-data]
verify_jwt = false

[functions.jarvis-agent]
verify_jwt = false