import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Brain, TrendingUp, TrendingDown, Minus, AlertCircle, CheckCircle, XCircle } from "lucide-react";
import { cn } from "@/lib/utils";

interface AIAnalysisProps {
  analysis: string;
  sentiment: 'bullish' | 'bearish' | 'neutral';
  valuation: 'overvalued' | 'undervalued' | 'fairly valued';
  symbol: string;
  timestamp: number;
}

export function AIAnalysis({ analysis, sentiment, valuation, symbol, timestamp }: AIAnalysisProps) {
  const getSentimentIcon = () => {
    switch (sentiment) {
      case 'bullish':
        return <TrendingUp className="h-5 w-5 text-bullish" />;
      case 'bearish':
        return <TrendingDown className="h-5 w-5 text-bearish" />;
      default:
        return <Minus className="h-5 w-5 text-neutral" />;
    }
  };

  const getValuationIcon = () => {
    switch (valuation) {
      case 'undervalued':
        return <CheckCircle className="h-5 w-5 text-bullish" />;
      case 'overvalued':
        return <XCircle className="h-5 w-5 text-bearish" />;
      default:
        return <AlertCircle className="h-5 w-5 text-neutral" />;
    }
  };

  const getSentimentColor = () => {
    switch (sentiment) {
      case 'bullish':
        return 'bg-bullish/20 border-bullish/50';
      case 'bearish':
        return 'bg-bearish/20 border-bearish/50';
      default:
        return 'bg-neutral/20 border-neutral/50';
    }
  };

  const formatTime = (timestamp: number) => {
    return new Date(timestamp).toLocaleTimeString();
  };

  return (
    <Card className={cn("p-6 border-2 transition-all duration-200", getSentimentColor())}>
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Brain className="h-6 w-6 text-primary" />
            <h3 className="font-bold text-lg">VeritasPilot Analysis</h3>
          </div>
          <Badge variant="outline" className="font-mono">
            {symbol}
          </Badge>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div className="flex items-center gap-2">
            {getSentimentIcon()}
            <div>
              <p className="text-sm text-muted-foreground">Sentiment</p>
              <p className="font-semibold capitalize">{sentiment}</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {getValuationIcon()}
            <div>
              <p className="text-sm text-muted-foreground">Valuation</p>
              <p className="font-semibold capitalize">{valuation}</p>
            </div>
          </div>
        </div>

        <div className="bg-background/50 rounded-lg p-4 border border-border">
          <p className="text-sm leading-relaxed whitespace-pre-wrap">{analysis}</p>
        </div>

        <div className="flex justify-between items-center text-xs text-muted-foreground">
          <span>Analysis generated by VeritasPilot AI</span>
          <span>Updated at {formatTime(timestamp)}</span>
        </div>
      </div>
    </Card>
  );
}