// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wssfoultuhczalslwdmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indzc2ZvdWx0dWhjemFsc2x3ZG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTQ1NzYsImV4cCI6MjA1OTkzMDU3Nn0.yux-Cnu05smO9WaDq6T6CkFgDRTo44YwmqZRqFp223I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});