// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzkycacuovszpcioeusm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6a3ljYWN1b3ZzenBjaW9ldXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjY5ODEsImV4cCI6MjA2NjUwMjk4MX0.8btCzZJPTfKLO5EEEvnNuycC17ziqr9161POGIjLFVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});